### ISSUE TITLE
HOMM2 Campaign support?

### ISSUE THREAD

**Issue by n3rd4i** [ciplogic/fheroes2enh#19]
I tried yesterday the engine but I could not figure out why the campaign was not appearing the the game menu. Is this a known issue or something I'm missing?

I'm trying to use the DOS version 1.1 of the game.

**Comment by ciplogic** [comment]
Campaign was never supported as it has a separate file format (I assume it is mostly the same, but it is not the same). 

There are also more pressing issues for this engine/game so I cannot assume that the campaign would be critical.

**Comment by lpalgarvio** [comment]
Price of Loyalty expansion campaigns might also have a slightly different format.

**Comment by lpalgarvio** [comment]
Perhaps work can be shared with the VCMI project?
Some formats might be similar.
https://github.com/vcmi/vcmi

**Comment by ciplogic** [comment]
Yes, and not sure if it will worth the work.

I think that if I would want to contribute there would be either:
* small glitches
* fixing AI
* fixing graphics engine to use SDL 2 (it was definitely very buggy when I tested it) instead of SDL 1.2.  Or maybe any other library with 2D acceleration and drawing in batches. This should fix also MacOS build

**Comment by ciplogic** [comment]
As for VCMI: contributions for both projects are definitely very welcomed by any of these projects. As people can notice, I slowed down with releases because of ... life. There is a bigger reward to care about my small child than to fix all bugs or look into binary formats :)

**Comment by n3rd4i** [comment]
I guess there is no time for this, closing for being stall
