### ISSUE TITLE
Assets from full game

### ISSUE THREAD

**Issue by lpalgarvio** [ciplogic/fheroes2enh#25]
Hello

Any way to use the assets from the full game?
- Music in CD Audio (with opera they call it)
- Maps

**Comment by ciplogic** [comment]
As for maps yes: by default it works with both Heroes 2 and the expansion maps.

As for CD, I disabled the code as I had compilation error from the old codebase and I also don't have a CD on my machine (I had the original game, but the CD is scrapped somewhere). 

Technically nothing stops you to play the CD as is, but it is not that cool than to be in-game.

Yes, I remember the opera music and it was amazing!

**Comment by ciplogic** [comment]
A side comment on notes: the maps downloaded with FHeroes2 are compiled by other guys and I just added them to the default installation, so you can technically take the maps of FH2Enhanced and add them to your Heroes 2 game. They should work.

You cannot share the save files which are internal for FHeroes2 engines.

**Comment by ihhub** [comment]
The answer is no. It's a property of Ubisoft.

**Comment by ciplogic** [comment]
I think this issue is resolved: 

* you can use FreeHeroes2 or FreeHeroe2Enhanced if copied in the original's game folder and you can play using original assets
* we cannot pack original game because of property rights which belong rightfully to Ubisoft. What we do though, installer automates downloading of Heroes 2 Demo for assets.
