### ISSUE TITLE
Why do we need C++14?

### ISSUE THREAD

**Issue by ihhub** [ciplogic/fheroes2enh#31]
The project uses C++14, what's the real need for it? Is C++11 not enough?

**Comment by ciplogic** [comment]
C is enough. My hope and assumption is that most people in 10 years from now would code in C++ 20 or similar, and will not look into contributing into C++ 03 or 11 coding because is "so old school".

I didn't use C++ 17 yet as compilers are not mature enough. 

But yes, C++ 14 doesn't make the code amazingly more readable because C++ 14 is basically 11 with very small bug fixes.
