### ISSUE TITLE
Why balance change was added?

### ISSUE THREAD

**Issue by ihhub** [ciplogic/fheroes2enh#32]
Shouldn't be an option to have rebalancing compare to original game? Who decided that such rebalance is correct? Is it just a personal opinion?

**Comment by ciplogic** [comment]
I decided after playing the patch for some time.

The point of the Enhancement fork was to make it a bit friendlier using conventions of present, not to be a port-accurate release. 

Probably it would be nicer to have a config that gets these values and people can change using "new set" and "original set". The problem is simply that it obviously this takes some time to write it, to test it, and most people would not change the default.

These kind of rebalances are in other FOSS recreations of games, i.e. OpenRA is one very good example.

**Comment by ciplogic** [comment]
Read the history of merge here:
https://github.com/ciplogic/fheroes2enh/pull/21
